// This file is auto-generated by test/devel/convert_redirects.py
// Do not edit by hand.


export const redirects: Record<string, string> = {
  "^/about/enroll/?$": "/about/policies/enroll/",
  "^/about/nondiscrimination\\-policy/?$": "/about/policies/nondiscrimination-policy/",
  "^/about/privacy\\-policy/?$": "/about/policies/privacy-policy/",
  "^/coding\\-camps/?$": "/coding-programs/coding-camps/",
  "^/coding\\-programs/introduction\\-to\\-programming\\-workshop/?$": "/coding-programs/workshop/",
  "^/coding\\-programs/java/?$": "/coding-programs/classes/",
  "^/coding\\-programs/programming\\-merit\\-badge/?$": "/coding-programs/tech-club/programming-merit-badge/",
  "^/coding\\-programs/python/?$": "/coding-programs/classes/",
  "^/coding\\-programs/robot\\-garage/?$": "/coding-programs/tech-club/robot-garage/",
  "^/contact/?$": "/about/contact/",
  "^/java/?$": "/coding-programs/java/",
  "^/l/tech\\-club/?$": "/coding-programs/tech-club/",
  "^/league\\-labs/?$": "https://www.jointheleague.org/coding-programs/league-labs",
  "^/locations/?$": "/about/locations/",
  "^/modal\\-camp\\-description/?$": "/modals/modal-camp-description/",
  "^/modal\\-creation/?$": "/modals/modal-creation/",
  "^/nondiscrimination\\-policy/?$": "/about/nondiscrimination-policy/",
  "^/policies/?$": "/about/policies/",
  "^/privacy\\-policy/?$": "/about/privacy-policy/",
  "^/programs/?$": "/coding-programs/",
  "^/python/?$": "/coding-programs/classes/",
  "^/qr/jtl/?$": "/",
  "^/sdcs\\-league\\-volunteers/?$": "/donate/sdcs-league-volunteers/",
  "^/summer\\-camp/?$": "/coding-programs/summer-camp/",
  "^/summer\\-camps/?$": "/summer-camp/",
  "^/techclub/?(?:\\?.*)?$": "https://www.meetup.com/the-league-tech-club/",
  "^/tuition\\-assistance/?$": "/about/tuition-assistance/",
  "^/volunteer/?$": "/donate/volunteer/",
};
